### ISSUE TITLE
German umlauts aren't decoded in exported .json for characters with a lot of custom items

### ISSUE THREAD

**Issue by Zebaoth93** [elyukai/optolith-client#1264] opened 2021-06-02 18:33 UTC
## Describe the bug

When you try to export a character that has a lot of custom items, the resulting .json does not include the german umlauts like ü, but characters like Ã¼.

## To Reproduce

1. Create a character
2. Add a lot of items
3. Modify items carrying location to something with an umlaut
4. Modify the item amount
5. Modify several item names
4. Export .json
5. See error

## Expected behavior

The umlauts should be properly present in the .json

## Environment

Please complete the following information:

- OS: Windows 7
- Version: newest

## Additional context

**Healthy .json with not so many items:**

{"clientVersion":"1.4.2","dateCreated":"2018-12-01T23:52:26.044Z","dateModified":"2021-06-02T14:03:00.797Z","id":"H_1622642520467","phase":3,"locale":"de-DE","name":"Lanan Ketten-Lanan Beerko","ap":{"total":1358},"el":"EL_3","r":"R_1","rv":"RV_2","c":"C_16","p":"P_8","pv":"PV_29","sex":"m","pers":{"family":"Eltern, 2 Brüder","placeofbirth":"Svallmund","dateofbirth":"7. Peraine, 1014 BF","age":"27","haircolor":10,"eyecolor":3,"size":"192","weight":"98","socialstatus":2,"characteristics":"Vollbart, Narbe auf der linken Wange","cultureAreaKnowledge":"Svallmund und Umgebung"},"attr":{"values":[{"id":"ATTR_1","value":11},{"id":"ATTR_2","value":12},{"id":"ATTR_3","value":12},{"id":"ATTR_4","value":10},{"id":"ATTR_5","value":11},{"id":"ATTR_6","value":16},{"id":"ATTR_7","value":13},{"id":"ATTR_8","value":13}],"attributeAdjustmentSelected":"ATTR_6","ae":0,"kp":0,"lp":0,"permanentAE":{"lost":0,"redeemed":0},"permanentKP":{"lost":0,"redeemed":0},"permanentLP":{"lost":0}},"activatable":{"ADV_50":[{}],"ADV_7":[{}],"ADV_17":[{"sid":"CT_4"}],"ADV_38":[{}],"ADV_41":[{}],"DISADV_5":[],"DISADV_3":[{}],"DISADV_33":[{"sid2":"Orks","sid":7}],"DISADV_37":[{"sid":9}],"SA_46":[{}],"SA_165":[{}],"SA_45":[{}],"SA_4":[{}],"SA_9":[{"sid2":2,"sid":"TAL_24"}],"SA_27":[{"sid":9}],"SA_29":[{"sid":8,"tier":4},{"sid":14,"tier":2},{"sid":12,"tier":3}],"SA_56":[{"tier":1}],"SA_115":[{}],"SA_117":[{}],"SA_183":[{}],"SA_679":[{}],"SA_99":[{}],"SA_41":[{"tier":1}]},"talents":{"TAL_3":6,"TAL_4":9,"TAL_5":6,"TAL_6":4,"TAL_7":4,"TAL_8":3,"TAL_10":6,"TAL_12":1,"TAL_13":6,"TAL_14":2,"TAL_17":6,"TAL_19":5,"TAL_20":5,"TAL_21":4,"TAL_22":5,"TAL_23":3,"TAL_24":9,"TAL_25":7,"TAL_27":6,"TAL_28":3,"TAL_29":1,"TAL_30":6,"TAL_34":3,"TAL_38":3,"TAL_39":5,"TAL_40":2,"TAL_45":2,"TAL_46":5,"TAL_50":3,"TAL_51":8,"TAL_52":1,"TAL_54":8,"TAL_15":2,"TAL_35":5,"TAL_37":1,"TAL_36":2,"TAL_57":1},"ct":{"CT_1":12,"CT_3":12,"CT_4":16,"CT_9":10,"CT_11":13},"spells":{"SPELL_3":7,"SPELL_147":14,"SPELL_31":11},"cantrips":[],"liturgies":{},"blessings":[],"belongings":{"items":{"ITEM_1":{"id":"ITEM_1","name":"Iryanrüstung","gr":4,"isTemplateLocked":true,"amount":1,"weight":5,"price":250,"enc":1,"pro":3,"template":"ITEMTPL_466","armorType":4},"ITEM_2":{"id":"ITEM_2","name":"Rapier","gr":1,"isTemplateLocked":true,"amount":1,"weight":1,"price":200,"at":1,"damageDiceNumber":1,"damageFlat":3,"length":100,"pa":0,"combatTechnique":"CT_4","damageDiceSides":6,"reach":2,"template":"ITEMTPL_9","primaryThreshold":{"threshold":15}},"ITEM_3":{"id":"ITEM_3","name":"Dolch","gr":1,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":45,"at":0,"damageDiceNumber":1,"damageFlat":1,"length":30,"pa":0,"combatTechnique":"CT_3","damageDiceSides":6,"reach":1,"template":"ITEMTPL_2","primaryThreshold":{"threshold":14}}},"armorZones":{"ARMORZONES_1":{"id":"ARMORZONES_1","name":"Reiserüstung","head":"ITEMTPL_82","leftArm":"ITEMTPL_84","rightArm":"ITEMTPL_84","torso":"ITEMTPL_84","leftLeg":"ITEMTPL_84","rightLeg":"ITEMTPL_84"}},"purse":{"d":"204","s":"7","h":"7","k":"1"}},"rules":{"higherParadeValues":0,"attributeValueLimit":false,"enableAllRuleBooks":true,"enabledRuleBooks":[],"enableLanguageSpecializations":false},"pets":{}}

**Broken .json with more items:**

{"clientVersion":"1.4.2","dateCreated":"2018-12-01T23:52:26.044Z","dateModified":"2021-06-02T13:53:58.738Z","id":"H_1543706273430","phase":3,"locale":"de-DE","name":"Lanan Ketten-Lanan Beerko","ap":{"total":1358},"el":"EL_3","r":"R_1","rv":"RV_2","c":"C_16","p":"P_8","pv":"PV_29","sex":"m","pers":{"family":"Eltern, 2 BrÃ¼der","placeofbirth":"Svallmund","dateofbirth":"7. Peraine, 1014 BF","age":"27","haircolor":10,"eyecolor":3,"size":"192","weight":"98","socialstatus":2,"characteristics":"Vollbart, Narbe auf der linken Wange","cultureAreaKnowledge":"Svallmund und Umgebung"},"attr":{"values":[{"id":"ATTR_1","value":11},{"id":"ATTR_2","value":12},{"id":"ATTR_3","value":12},{"id":"ATTR_4","value":10},{"id":"ATTR_5","value":11},{"id":"ATTR_6","value":16},{"id":"ATTR_7","value":13},{"id":"ATTR_8","value":13}],"attributeAdjustmentSelected":"ATTR_6","ae":0,"kp":0,"lp":0,"permanentAE":{"lost":0,"redeemed":0},"permanentKP":{"lost":0,"redeemed":0},"permanentLP":{"lost":0}},"activatable":{"ADV_50":[{}],"ADV_7":[{}],"ADV_17":[{"sid":"CT_4"}],"ADV_38":[{}],"ADV_41":[{}],"DISADV_5":[],"DISADV_3":[{}],"DISADV_33":[{"sid2":"Orks","sid":7}],"DISADV_37":[{"sid":9}],"SA_46":[{}],"SA_165":[{}],"SA_45":[{}],"SA_4":[{}],"SA_9":[{"sid2":2,"sid":"TAL_24"}],"SA_27":[{"sid":9}],"SA_29":[{"sid":8,"tier":4},{"sid":14,"tier":2},{"sid":12,"tier":3}],"SA_56":[{"tier":1}],"SA_115":[{}],"SA_117":[{}],"SA_183":[{}],"SA_679":[{}],"SA_99":[{}],"SA_41":[{"tier":1}]},"talents":{"TAL_3":6,"TAL_4":9,"TAL_5":6,"TAL_6":4,"TAL_7":4,"TAL_8":3,"TAL_10":6,"TAL_12":1,"TAL_13":6,"TAL_14":2,"TAL_17":6,"TAL_19":5,"TAL_20":5,"TAL_21":4,"TAL_22":5,"TAL_23":3,"TAL_24":9,"TAL_25":7,"TAL_27":6,"TAL_28":3,"TAL_29":1,"TAL_30":6,"TAL_34":3,"TAL_38":3,"TAL_39":5,"TAL_40":2,"TAL_45":2,"TAL_46":5,"TAL_50":3,"TAL_51":8,"TAL_52":1,"TAL_54":8,"TAL_15":2,"TAL_35":5,"TAL_37":1,"TAL_36":2,"TAL_57":1},"ct":{"CT_1":12,"CT_3":12,"CT_4":16,"CT_9":10,"CT_11":13},"spells":{"SPELL_3":7,"SPELL_147":14,"SPELL_31":11},"cantrips":[],"liturgies":{},"blessings":[],"belongings":{"items":{"ITEM_2":{"id":"ITEM_2","name":"Armreif, Silber (Artefaktgebunden)","gr":15,"isTemplateLocked":false,"amount":1,"weight":0.05,"price":10,"at":0,"damageDiceNumber":0,"damageFlat":0,"enc":0,"length":0,"pa":0,"pro":0,"reloadTime":0,"stp":0,"template":"ITEMTPL_246","where":"Handgelenk (links)","range":[0,0,0]},"ITEM_3":{"id":"ITEM_3","name":"Kleidungsset: Frei","gr":6,"isTemplateLocked":true,"amount":1,"price":25,"template":"ITEMTPL_139","where":"KÃ¶rper"},"ITEM_4":{"id":"ITEM_4","name":"LedergÃ¼rtel","gr":6,"isTemplateLocked":true,"amount":1,"price":3,"template":"ITEMTPL_109","where":"KÃ¶rper"},"ITEM_5":{"id":"ITEM_5","name":"Lederstiefel (wasserfest)","gr":6,"isTemplateLocked":false,"amount":1,"price":12,"template":"ITEMTPL_115","where":"KÃ¶rper"},"ITEM_6":{"id":"ITEM_6","name":"Schwertscheide","gr":5,"isTemplateLocked":true,"amount":2,"price":12,"template":"ITEMTPL_91","where":"LedergÃ¼rtel"},"ITEM_9":{"id":"ITEM_9","name":"Lederrucksack","gr":10,"isTemplateLocked":true,"amount":1,"price":34,"template":"ITEMTPL_205","where":"KÃ¶rper"},"ITEM_10":{"id":"ITEM_10","name":"Geldbeutel","gr":10,"isTemplateLocked":true,"amount":1,"price":1,"template":"ITEMTPL_200","where":"GÃ¼rteltasche"},"ITEM_11":{"id":"ITEM_11","name":"Feldflasche","gr":10,"isTemplateLocked":true,"amount":1,"price":6,"template":"ITEMTPL_199","where":"Lederrucksack"},"ITEM_12":{"id":"ITEM_12","name":"Tuchbeutel","gr":10,"isTemplateLocked":true,"amount":5,"price":0.75,"template":"ITEMTPL_213","where":"Lederrucksack"},"ITEM_14":{"id":"ITEM_14","name":"Essbesteck","gr":7,"isTemplateLocked":true,"amount":1,"price":0.5,"template":"ITEMTPL_150","where":"Lederrucksack"},"ITEM_15":{"id":"ITEM_15","name":"Pfanne","gr":7,"isTemplateLocked":true,"amount":1,"price":12,"template":"ITEMTPL_169","where":"Lederrucksack (auÃŸen)"},"ITEM_17":{"id":"ITEM_17","name":"Proviant fÃ¼r 1 Tag","gr":7,"isTemplateLocked":true,"amount":2,"price":0.5,"template":"ITEMTPL_181","where":"Lederrucksack"},"ITEM_18":{"id":"ITEM_18","name":"Fesselseil, Hanf, pro Schritt","gr":11,"isTemplateLocked":true,"amount":10,"price":0.3,"template":"ITEMTPL_217","where":"Lederrucksack"},"ITEM_19":{"id":"ITEM_19","name":"GÃ¶tterfigÃ¼rchen (Boron)","gr":24,"isTemplateLocked":false,"amount":1,"weight":0.2,"price":3,"at":0,"damageDiceNumber":0,"damageFlat":0,"enc":0,"length":0,"pa":0,"pro":0,"reloadTime":0,"stp":0,"template":"ITEMTPL_334","where":"GÃ¼rteltasche","range":[0,0,0]},"ITEM_20":{"id":"ITEM_20","name":"Spielkarten","gr":24,"isTemplateLocked":true,"amount":1,"price":5,"template":"ITEMTPL_350","where":"GÃ¼rteltasche"},"ITEM_21":{"id":"ITEM_21","name":"Seife","gr":24,"isTemplateLocked":true,"amount":1,"price":1,"template":"ITEMTPL_349","where":"Tuchbeutel"},"ITEM_22":{"id":"ITEM_22","name":"GÃ¼rteltasche","gr":10,"isTemplateLocked":true,"amount":1,"price":4,"template":"ITEMTPL_202","where":"LedergÃ¼rtel"},"ITEM_23":{"id":"ITEM_23","name":"Beil/Handaxt","gr":7,"isTemplateLocked":true,"amount":1,"price":20,"template":"ITEMTPL_145","where":"Lederrucksack (auÃŸen)"},"ITEM_24":{"id":"ITEM_24","name":"Kohlestift","gr":17,"isTemplateLocked":true,"amount":2,"price":0.2,"template":"ITEMTPL_284","where":"Tuchbeutel"},"ITEM_25":{"id":"ITEM_25","name":"Papier, 1 Blatt","gr":17,"isTemplateLocked":true,"amount":6,"price":0.1,"template":"ITEMTPL_286","where":"Tuchbeutel"},"ITEM_26":{"id":"ITEM_26","name":"Siegelwachs, alle Farben","gr":17,"isTemplateLocked":false,"amount":6,"price":3,"template":"ITEMTPL_289","where":"Tuchbeutel"},"ITEM_27":{"id":"ITEM_27","name":"Tinte","gr":17,"isTemplateLocked":true,"amount":1,"price":1,"template":"ITEMTPL_291","where":"Tuchbeutel"},"ITEM_28":{"id":"ITEM_28","name":"Federmesser","gr":17,"isTemplateLocked":true,"amount":1,"price":3,"template":"ITEMTPL_283","where":"Lederstiefel (rechts)"},"ITEM_29":{"id":"ITEM_29","name":"Federkiel","gr":17,"isTemplateLocked":true,"amount":1,"price":0.1,"template":"ITEMTPL_282","where":"Tuchbeutel"},"ITEM_30":{"id":"ITEM_30","name":"Feuerstein und Stahl","gr":8,"isTemplateLocked":true,"amount":1,"price":3,"template":"ITEMTPL_188","where":"GÃ¼rteltasche"},"ITEM_31":{"id":"ITEM_31","name":"Fackel","gr":8,"isTemplateLocked":true,"amount":1,"price":0.5,"template":"ITEMTPL_182","where":"Lederrucksack (auÃŸen)"},"ITEM_32":{"id":"ITEM_32","name":"Jagdmesser","gr":1,"isTemplateLocked":true,"amount":1,"price":50,"template":"ITEMTPL_444","where":"Dolchscheide"},"ITEM_33":{"id":"ITEM_33","name":"Dolchscheide","gr":5,"isTemplateLocked":true,"amount":1,"price":5,"template":"ITEMTPL_89","where":"LedergÃ¼rtel"},"ITEM_36":{"id":"ITEM_36","name":"Rapier","gr":1,"isTemplateLocked":false,"amount":2,"weight":1,"price":200,"at":1,"damageDiceNumber":1,"damageFlat":3,"length":100,"pa":1,"combatTechnique":"CT_4","damageDiceSides":6,"reach":2,"template":"ITEMTPL_9","where":"Schwertscheide","primaryThreshold":{"threshold":15}},"ITEM_37":{"id":"ITEM_37","name":"Schnaps","gr":24,"isTemplateLocked":true,"amount":3,"weight":1,"price":2,"template":"ITEMTPL_346","where":"Lederrucksack"},"ITEM_38":{"id":"ITEM_38","name":"Zelt, 2 Personen","gr":7,"isTemplateLocked":true,"amount":1,"weight":6,"price":25,"stp":7,"template":"ITEMTPL_180","where":"Sattel (auÃŸen)"},"ITEM_39":{"id":"ITEM_39","name":"Schlafsack","gr":7,"isTemplateLocked":true,"amount":1,"weight":2,"price":7,"stp":7,"template":"ITEMTPL_172","where":"Lederrucksack"},"ITEM_40":{"id":"ITEM_40","name":"KÃ¶nig der Gaukler - MÃ¼tze","gr":6,"isTemplateLocked":false,"amount":1,"weight":0.1,"price":0.8,"template":"ITEMTPL_132","where":"Lederrucksack"},"ITEM_41":{"id":"ITEM_41","name":"Verzierter Umhang (rot)","gr":6,"isTemplateLocked":false,"amount":1,"weight":1.5,"price":7,"stp":6,"template":"ITEMTPL_118","where":"KÃ¶rper"},"ITEM_42":{"id":"ITEM_42","name":"SchnÃ¼rsenkel","gr":11,"isTemplateLocked":false,"amount":2,"weight":0.1,"price":0.5,"template":"ITEMTPL_220","where":"Lederrucksack"},"ITEM_43":{"id":"ITEM_43","name":"Wurfnetz","gr":2,"isTemplateLocked":false,"amount":1,"weight":2,"price":35,"length":350,"reloadTime":1,"combatTechnique":"CT_11","template":"ITEMTPL_465","where":"LedergÃ¼rtel","range":[1,3,5]},"ITEM_44":{"id":"ITEM_44","name":"Papier, gutes, 1 Blatt","gr":17,"isTemplateLocked":true,"amount":4,"weight":0.05,"price":0.3,"stp":2,"template":"ITEMTPL_429","where":"Tuchbeutel"},"ITEM_45":{"id":"ITEM_45","name":"GÃ¶tterfigÃ¼rchen (Gobgott)","gr":24,"isTemplateLocked":false,"amount":1,"weight":0.2,"price":3,"stp":3,"template":"ITEMTPL_334","where":"Lederrucksack"},"ITEM_46":{"id":"ITEM_46","name":"Geschicklichkeitstrank","gr":20,"isTemplateLocked":false,"amount":1,"price":60,"template":"ITEMTPL_299","where":"GÃ¼rteltasche"},"ITEM_47":{"id":"ITEM_47","name":"Balestrina","gr":2,"isTemplateLocked":true,"amount":1,"weight":0.75,"price":120,"damageDiceNumber":1,"damageFlat":4,"length":40,"reloadTime":2,"ammunition":"ITEMTPL_77","combatTechnique":"CT_1","damageDiceSides":6,"template":"ITEMTPL_57","range":[5,25,40]},"ITEM_48":{"id":"ITEM_48","name":"Halstuch","gr":6,"isTemplateLocked":true,"amount":1,"weight":0.1,"price":4,"template":"ITEMTPL_99","where":"KÃ¶rper"},"ITEM_49":{"id":"ITEM_49","name":"Poncho","gr":6,"isTemplateLocked":false,"amount":1,"weight":1,"price":6,"template":"ITEMTPL_105","where":"Lederrucksack"},"ITEM_51":{"id":"ITEM_51","name":"Wurfhaken mit Kletterseil","gr":1,"isTemplateLocked":true,"amount":1,"weight":1.5,"price":7.3,"at":-2,"damageDiceNumber":1,"damageFlat":1,"length":100,"combatTechnique":"CT_6","damageDiceSides":6,"reach":3,"template":"ITEMTPL_442","where":"Sattel (auÃŸen)","primaryThreshold":{"threshold":14}},"ITEM_52":{"id":"ITEM_52","name":"Waffenpflegeset (Schleifstein, TÃ¼cher)","gr":5,"isTemplateLocked":true,"amount":1,"weight":1,"price":1,"template":"ITEMTPL_93","where":"Satteltasche"},"ITEM_53":{"id":"ITEM_53","name":"IryanrÃ¼stung","gr":4,"isTemplateLocked":true,"amount":1,"weight":5,"price":250,"enc":1,"pro":3,"template":"ITEMTPL_466","where":"KÃ¶rper","armorType":4},"ITEM_54":{"id":"ITEM_54","name":"Wurara","gr":21,"isTemplateLocked":true,"amount":3,"price":100,"template":"ITEMTPL_309","where":"GÃ¼rteltasche"},"ITEM_55":{"id":"ITEM_55","name":"Zange","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":6,"template":"ITEMTPL_178","where":"Werkzeugtasche"},"ITEM_56":{"id":"ITEM_56","name":"Spaten","gr":7,"isTemplateLocked":true,"amount":1,"weight":2,"price":8.5,"at":-2,"damageDiceNumber":1,"damageFlat":4,"length":90,"pa":-4,"stp":15,"combatTechnique":"CT_15","damageDiceSides":6,"reach":2,"template":"ITEMTPL_174","where":"Sattel (auÃŸen)","primaryThreshold":{"threshold":13}},"ITEM_57":{"id":"ITEM_57","name":"Schere","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.25,"price":5,"template":"ITEMTPL_171","where":"Werkzeugtasche"},"ITEM_58":{"id":"ITEM_58","name":"Leim","gr":7,"isTemplateLocked":true,"amount":1,"weight":1,"price":1,"template":"ITEMTPL_164","where":"Werkzeugtasche"},"ITEM_59":{"id":"ITEM_59","name":"MeiÃŸel","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.2,"price":5.5,"template":"ITEMTPL_165","where":"Werkzeugtasche"},"ITEM_60":{"id":"ITEM_60","name":"HandsÃ¤ge","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":5,"template":"ITEMTPL_155","where":"Werkzeugtasche"},"ITEM_61":{"id":"ITEM_61","name":"Feile","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":15,"template":"ITEMTPL_151","where":"Werkzeugtasche"},"ITEM_62":{"id":"ITEM_62","name":"Hammer","gr":7,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":3,"template":"ITEMTPL_153","where":"Werkzeugtasche"},"ITEM_63":{"id":"ITEM_63","name":"Handbohrer","gr":7,"isTemplateLocked":true,"amount":1,"weight":1,"price":7,"template":"ITEMTPL_154","where":"Werkzeugtasche"},"ITEM_64":{"id":"ITEM_64","name":"NÃ¤gel, 10 StÃ¼ck","gr":7,"isTemplateLocked":true,"amount":10,"weight":0.1,"price":0.6,"template":"ITEMTPL_168","where":"Werkzeugtasche"},"ITEM_65":{"id":"ITEM_65","name":"Werkzeugtasche","gr":13,"isTemplateLocked":false,"amount":1,"weight":2,"price":50,"template":"ITEMTPL_233","where":"Sattel (auÃŸen)"},"ITEM_66":{"id":"ITEM_66","name":"Gravurwerkzeug","gr":13,"isTemplateLocked":true,"amount":1,"weight":0.5,"price":30,"template":"ITEMTPL_229","where":"Werkzeugtasche"},"ITEM_67":{"id":"ITEM_67","name":"Holzrohling","gr":13,"isTemplateLocked":false,"amount":20,"weight":0.125,"price":1,"stp":10,"template":"ITEMTPL_722","where":"Werkzeugtasche"},"ITEM_68":{"id":"ITEM_68","name":"Heiltrank","gr":20,"isTemplateLocked":true,"amount":1,"price":60,"template":"ITEMTPL_299","where":"GÃ¼rteltasche"}},"armorZones":{"ARMORZONES_1":{"id":"ARMORZONES_1","name":"ReiserÃ¼stung","head":"ITEMTPL_82","leftArm":"ITEMTPL_84","rightArm":"ITEMTPL_84","torso":"ITEMTPL_84","leftLeg":"ITEMTPL_84","rightLeg":"ITEMTPL_84"}},"purse":{"d":"204","s":"7","h":"7","k":"1"}},"rules":{"higherParadeValues":0,"attributeValueLimit":false,"enableAllRuleBooks":true,"enabledRuleBooks":[],"enableLanguageSpecializations":false},"pets":{}}

**Comment by pickbreaker** [comment] 2021-06-02 19:25
Can't confirm on Win 10 Build 21390, Opto Versions 1.4.2 and 1.5.0-alpha.1

**Comment by elyukai** [comment] 2021-06-05 07:22
Thanks for your report!

It may have to do with Windows 7 since it reached end of life and is thus not supported anymore by the framework I use. 

I will upgrade to the latest version of it with the upcoming 1.5.0 release, maybe this will fix it. Otherwise I need to further investigate what could be the cause of the issue, but, as I said, it might just have to do with your OS.

**Comment by phispi** [comment] 2021-06-08 20:16
I just tried it with version 1.4.2 on my system (Debian Linux) and the exported .json contains correctly encoded UTF-8 German umlauts ("ü" as in "Rüstung" represented as hex "c3 bc" as it should be in UTF-8). The fact the JSON needs to use UTF-8 is defined in RFC 8259: "JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8").

I had a closer look at the files you provided and it seems that they are correct but the editor you used to open the JSON file was not using UTF-8 encoding but assumed something like ISO8859-1 or a comparable codepage which was quite common for Windows 7 programs. Opening a JSON file with an editor assuming ISO8859-15 would show "ü" as "Ã¼" which is exactly what your example shows. I would recommend to open your JSON files with an UTF-8 aware editor (like Notepad++ in UTF-8 mode). Alternatively you could view your JSON files with a HEX editor and see what byte(s) "ü" consists of ("c3 bc" would be correct).

**Comment by elyukai** [comment] 2021-06-08 20:20
Thanks a lot for your contribution! 😮 I haven't thought of *that* … 😬🙈

**Comment by Zebaoth93** [comment] 2021-06-09 05:34
Thank you very much, didn't think of the editor, since both files were opened with it and the first ones umlauts were shown as intended. (e.g. "family":"Eltern, 2 Brüder"}

**Comment by elyukai** [comment] 2021-06-09 06:29
I seems like this was/is the solution, so I'm going to close this issue. If I'm wrong, feel free to reopen! 😅🙈

**Closed by elyukai** 2021-06-09 06:29 UTC
Labels: Bug, Domain: IO, Needs Investigation
