### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by thebodo** [elyukai/optolith-client#588] opened 2020-05-18 21:03 UTC
**Describe the bug**
Import not working on Mac OS 10.15.4

**To Reproduce**

1. Go to 'Helden'
2. Click on 'Importieren'
3. Select an JSON-File exported earlier
4. Click on "Öffnen"
5. Nothing happens

**Expected behavior**
That the file would be imported (or at least an error message if the file is corrupted)

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac OS 10.15.4
- Version: Optolith Desktop Client V1.2.0

**Additional context**
I also checked the console of the "developer tools" no error there.

**Comment by elyukai** [comment] 2020-05-18 21:08
Would it be possible to attach the JSON you used when you encountered that bug? You can also send it to me via e-mail, whatever you prefer. Then searching for the cause of the issue would be a lot easier. 🙈

Thanks in advance and thanks for your report!!! 🤗🥰

**Comment by thebodo** [comment] 2020-05-18 21:34
I just updated manually to 1.3.2 and the issue is gone.
I received the json from a friend and will ask tomorrow whether I may provide it.
I have now seen that the JSON was created with version 1.3.2 so that might be the reason.

**Comment by elyukai** [comment] 2020-05-18 21:37
Hmm, Optolith does provide support for imported heroes created with older versions of Optolith. 🤔 There are some *very* old versions that are not supported anymore, but they are like three years old so I don't think your friend still uses them! 😅

**Comment by elyukai** [comment] 2020-09-18 21:14
Sorry for this late comment here, I just went through all the missing issues for the next release and saw I didn't close this one... 🙈🙈🙈 

If you remember the case, do you know if your friend used a *newer* version than what you used?

**Comment by elyukai** [comment] 2021-05-27 09:28
Okay, it seems like I can't properly read. The newer version is very likely the reason, so I'm gonna close this. I do will improve on any alert message for those cases, tho.

**Closed by elyukai** 2021-05-27 09:28 UTC
Labels: Bug, Domain: IO, Needs Investigation
