### ISSUE TITLE
Witch (Artist / Fahrende Schwester) with wrong special ability

### ISSUE THREAD

**Issue by Tandosch** [elyukai/optolith-client#1332] opened 2021-12-18 15:46 UTC
## Witch (Fahrende Schwester / Artist) contains wrong spicial Abilies

By creating a Witch (Artist / fahrende Schwester) you cannot select special magical Abilies "Bewegungshexerei" or "Meisterliches Aura verbergen".

Instead of this the abiliy "Kesselmeisterin" is avaiable.

- OS: [Windows 10]
- Version: [e.g. 1.5.1, 1.3.0-alpha.5]

**Comment by elyukai** [comment] 2022-02-03 20:23
Please check again with current prerelease (1.5.0-alpha.7). For me, all three Advanced Magical Special Abilities are available: 

- *Kesselmeisterin* is one of them.
- *Begegnungshexerei* is called *Bewegungszauberei*.
- *Meisterliches Aura verbergen* has *Aura verbergen* as a prerequisite. If you have that, it should be activatable as well.

Thank you! 🙏🏻

**Comment by elyukai** [comment] 2022-02-05 10:37
I and others cant reproduce this issue, so I'm gonna close it. Please reopen if it still applies to the latest prerelease.

**Closed by elyukai** 2022-02-05 10:37 UTC
Labels: Bug, Needs More Info
